// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsteticaPorDoSol.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603040946_TelefoneOpcional")]
    partial class TelefoneOpcional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EsteticaPorDoSol.Models.Atendimento", b =>
                {
                    b.Property<int>("idAtendimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idAtendimento"));

                    b.Property<string>("dsStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dtDataHoraAtendimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("dtDataHoraSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("idVeiculo")
                        .HasColumnType("int");

                    b.Property<decimal>("vlTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("idAtendimento");

                    b.HasIndex("idCliente");

                    b.HasIndex("idVeiculo");

                    b.ToTable("tbAtendimentos");
                });

            modelBuilder.Entity("EsteticaPorDoSol.Models.AtendimentoServico", b =>
                {
                    b.Property<int>("idAtendimentoServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idAtendimentoServico"));

                    b.Property<int>("idAtendimento")
                        .HasColumnType("int");

                    b.Property<int>("idServico")
                        .HasColumnType("int");

                    b.Property<decimal>("vlServicoNoMomento")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("idAtendimentoServico");

                    b.HasIndex("idAtendimento");

                    b.HasIndex("idServico");

                    b.ToTable("tbAtendimentoServicos");
                });

            modelBuilder.Entity("EsteticaPorDoSol.Models.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idCliente"));

                    b.Property<string>("dsNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nrTelefone")
                        .HasColumnType("longtext");

                    b.HasKey("idCliente");

                    b.ToTable("tbClientes");
                });

            modelBuilder.Entity("EsteticaPorDoSol.Models.Servico", b =>
                {
                    b.Property<int>("idServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idServico"));

                    b.Property<string>("dsDescricaoServico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("dsNomeServico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("vlServico")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("idServico");

                    b.ToTable("tbServicos");
                });

            modelBuilder.Entity("EsteticaPorDoSol.Models.Veiculo", b =>
                {
                    b.Property<int>("idVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idVeiculo"));

                    b.Property<string>("dsCor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("dsModelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("dsPlaca")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.HasKey("idVeiculo");

                    b.HasIndex("idCliente");

                    b.ToTable("tbVeiculos");
                });

            modelBuilder.Entity("EsteticaPorDoSol.Models.Atendimento", b =>
                {
                    b.HasOne("EsteticaPorDoSol.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsteticaPorDoSol.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("idVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("EsteticaPorDoSol.Models.AtendimentoServico", b =>
                {
                    b.HasOne("EsteticaPorDoSol.Models.Atendimento", "Atendimento")
                        .WithMany("AtendimentoServicos")
                        .HasForeignKey("idAtendimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsteticaPorDoSol.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("idServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("EsteticaPorDoSol.Models.Veiculo", b =>
                {
                    b.HasOne("EsteticaPorDoSol.Models.Cliente", "Cliente")
                        .WithMany("Veiculos")
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("EsteticaPorDoSol.Models.Atendimento", b =>
                {
                    b.Navigation("AtendimentoServicos");
                });

            modelBuilder.Entity("EsteticaPorDoSol.Models.Cliente", b =>
                {
                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
